repository_type: pipeline
nf_core_version: 3.2.0

lint:
  pipeline_name_conventions: False # Ignore: Naming does not adhere to nf-core conventions: Contains uppercase letters
  schema_lint: False # Ignore: Parameter input not found in schema
  actions_awsfulltest: False
  pipeline_todos: False
  nextflow_config: False
  multiqc_config: False
  files_unchanged: False
  files_exist:
    - .gitattributes
    - .editorconfig
    - CHANGELOG.md
    - CITATIONS.md
    - CODE_OF_CONDUCT.md
    - .github/.dockstore.yml
    - .github/CONTRIBUTING.md
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/ISSUE_TEMPLATE/feature_request.yml
    - .github/PULL_REQUEST_TEMPLATE.md
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml
    - .github/workflows/branch.yml
    - .github/workflows/linting_comment.yml
    - .github/workflows/linting.yml
    - .github/workflows/ci.yml
    - assets/multiqc_config.yml
    - assets/email_template.html
    - assets/email_template.txt
    - assets/sendmail_template.txt
    - assets/nf-core-AI_MARRVEL_logo_light.png
    - conf/igenomes.config
    - conf/igenomes_ignored.config
    - conf/test.config
    - conf/test_full.config
    - docs/images/nf-core-AI_MARRVEL_logo_light.png
    - docs/images/nf-core-AI_MARRVEL_logo_dark.png
    - docs/output.md
    - docs/README.md
    - docs/README.md
    - docs/usage.md
    - ro-crate-metadata.json

template:
  org: nf-core
  name: aim
  description: testing template
  author: zahid shaik
  version: 1.0.0dev
  force: true
  outdir: .
  skip_features:
    - codespaces
    - fastqc
    - license
    - adaptivecard
    - seqera_platform
    - rocrate
  is_nfcore: false